/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JTextField;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author user
 */
public class frm_cadenas extends javax.swing.JFrame {
    JFileChooser seleccionar= new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    /**
     * Creates new form frm_cadenas
     */
    public frm_cadenas() {
        initComponents();
    }

    public String AbrirArchivo(File archivo){
        String documento="";
        try{
            entrada = new FileInputStream(archivo);
            int ascii;
            while ((ascii=entrada.read()) !=-1) {
                char caracter= (char) ascii;
                documento +=caracter;
            }
        }catch (Exception e) {
        }
        return documento;
    }
    
    public String GuardarArchivo(File archivo, String documento) {
        String mensaje = null;
        try{
            salida = new FileOutputStream (archivo) ;
            byte []  bytxt=documento.getBytes();
            salida.write(bytxt);
            mensaje= "Archivo Guardado";
        }catch(Exception e){
            
        }
        return mensaje;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        lbl_tittle = new javax.swing.JLabel();
        lbl_instruccion = new javax.swing.JLabel();
        txt_field = new javax.swing.JScrollPane();
        txt_updated = new javax.swing.JTextField();
        btn_procesar = new javax.swing.JButton();
        longitud_texto = new javax.swing.JLabel();
        total_palabras = new javax.swing.JLabel();
        primer_letra = new javax.swing.JLabel();
        ultima_letra = new javax.swing.JLabel();
        letra_central = new javax.swing.JLabel();
        primera_palabra = new javax.swing.JLabel();
        palabra_central = new javax.swing.JLabel();
        ultima_palabra = new javax.swing.JLabel();
        repeticiones_a = new javax.swing.JLabel();
        repeticiones_e = new javax.swing.JLabel();
        repeticiones_i = new javax.swing.JLabel();
        repeticiones_o = new javax.swing.JLabel();
        repeticiones_u = new javax.swing.JLabel();
        palabras_par = new javax.swing.JLabel();
        palabras_impar = new javax.swing.JLabel();
        clave_murcielago = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_murcielago = new javax.swing.JTextField();
        n_longitud = new javax.swing.JLabel();
        n_totalp = new javax.swing.JLabel();
        n_primeral = new javax.swing.JLabel();
        n_ultimal = new javax.swing.JLabel();
        n_centrall = new javax.swing.JLabel();
        n_primerap = new javax.swing.JLabel();
        n_palabrac = new javax.swing.JLabel();
        n_ultimap = new javax.swing.JLabel();
        letra_a = new javax.swing.JLabel();
        letra_e = new javax.swing.JLabel();
        letra_i = new javax.swing.JLabel();
        letra_o = new javax.swing.JLabel();
        letra_u = new javax.swing.JLabel();
        p_par = new javax.swing.JLabel();
        p_impar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jm_abrir = new javax.swing.JMenuItem();
        jm_guardar = new javax.swing.JMenuItem();
        jm_guardarComo = new javax.swing.JMenuItem();
        jm_editar = new javax.swing.JMenu();
        jm_copiar = new javax.swing.JMenuItem();
        jm_cortar = new javax.swing.JMenuItem();
        jm_pegar = new javax.swing.JMenuItem();
        jm_buscar = new javax.swing.JMenuItem();
        jm_reemplazar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        lbl_tittle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_tittle.setText("Manejo de Cadenas");

        lbl_instruccion.setText("Ingrese un texto o abra un archivo");

        txt_field.setViewportView(txt_updated);

        btn_procesar.setText("Procesar");
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });

        longitud_texto.setText("Longitud del texto");

        total_palabras.setText("Total de palabras");

        primer_letra.setText("Primera letra del texto");

        ultima_letra.setText("Letra central del texto");

        letra_central.setText("Ultima letra del texto");

        primera_palabra.setText("Primera palabra");

        palabra_central.setText("Palabra central");

        ultima_palabra.setText("Ultima palabra");

        repeticiones_a.setText("Repeticiones de \"A\", \"a\",  \"á\"");

        repeticiones_e.setText("Repeticiones de \"E\", \"e\",  \"é\"");

        repeticiones_i.setText("Repeticiones de \"I\", \"i\",  \"í\"");

        repeticiones_o.setText("Repeticiones de \"O\", \"o\",  \"ó\"");

        repeticiones_u.setText("Repeticiones de \"U\", \"u\",  \"ú\"");

        palabras_par.setText("Palabras con cantidad de caracteres par");

        palabras_impar.setText("Palabras con cantidad de caracteres impar");

        clave_murcielago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clave_murcielago.setText("TRADUCCIÓN A CLAVE MURCIELAGO");

        txt_murcielago.setEditable(false);
        jScrollPane1.setViewportView(txt_murcielago);

        jm_archivo.setText("Archivo");

        jm_abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_abrir.setText("Abrir");
        jm_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_abrirActionPerformed(evt);
            }
        });
        jm_archivo.add(jm_abrir);

        jm_guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_guardar.setText("Guardar");
        jm_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_guardarActionPerformed(evt);
            }
        });
        jm_archivo.add(jm_guardar);

        jm_guardarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_guardarComo.setText("Guardar Como");
        jm_guardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_guardarComoActionPerformed(evt);
            }
        });
        jm_archivo.add(jm_guardarComo);

        jMenuBar1.add(jm_archivo);

        jm_editar.setText("Editar");

        jm_copiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_copiar.setText("Copiar");
        jm_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_copiarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_copiar);

        jm_cortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_cortar.setText("Cortar");
        jm_cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_cortarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_cortar);

        jm_pegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_pegar.setText("Pegar");
        jm_pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_pegarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_pegar);

        jm_buscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_buscar.setText("Buscar");
        jm_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_buscarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_buscar);

        jm_reemplazar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_reemplazar.setText("Reemplazar");
        jm_reemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_reemplazarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_reemplazar);

        jMenuBar1.add(jm_editar);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_field)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_instruccion))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(btn_procesar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(longitud_texto)
                                    .addComponent(total_palabras)
                                    .addComponent(primer_letra)
                                    .addComponent(ultima_letra)
                                    .addComponent(letra_central)
                                    .addComponent(primera_palabra)
                                    .addComponent(palabra_central)
                                    .addComponent(ultima_palabra))
                                .addGap(26, 26, 26)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(n_longitud)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(n_palabrac)
                                            .addComponent(n_primerap)
                                            .addComponent(n_centrall)
                                            .addComponent(n_ultimal)
                                            .addComponent(n_primeral)
                                            .addComponent(n_totalp)
                                            .addComponent(n_ultimap))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(palabras_par)
                                                    .addComponent(repeticiones_u)
                                                    .addComponent(repeticiones_o)
                                                    .addComponent(repeticiones_i)
                                                    .addComponent(repeticiones_e)
                                                    .addComponent(palabras_impar))
                                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                        .addGap(20, 20, 20)
                                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(letra_e)
                                                            .addComponent(letra_i)
                                                            .addComponent(letra_o)
                                                            .addComponent(p_impar)
                                                            .addComponent(letra_u)))
                                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(p_par, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGap(6, 6, 6))
                                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(repeticiones_a)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(letra_a, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addGap(21, 21, 21))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(clave_murcielago))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lbl_tittle)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_instruccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_procesar)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(longitud_texto)
                            .addComponent(n_longitud))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total_palabras)
                            .addComponent(n_totalp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(primer_letra)
                            .addComponent(n_primeral))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ultima_letra)
                            .addComponent(n_ultimal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(letra_central)
                            .addComponent(n_centrall))
                        .addGap(0, 0, 0)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(primera_palabra)
                            .addComponent(n_primerap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(palabra_central)
                            .addComponent(n_palabrac))
                        .addGap(12, 12, 12)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ultima_palabra)
                            .addComponent(n_ultimap)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(letra_e)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letra_i)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letra_o)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letra_u)
                                .addGap(28, 28, 28)
                                .addComponent(p_impar))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(repeticiones_a)
                                    .addComponent(letra_a))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(repeticiones_e)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(repeticiones_i)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(repeticiones_o)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(repeticiones_u)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(palabras_par)
                                    .addComponent(p_par))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(palabras_impar)))))
                .addGap(121, 121, 121)
                .addComponent(clave_murcielago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed
        // TODO add your handling code here:
        String cadena = this.txt_updated.getText();
        
        int n_longi = cadena.length();
        n_longitud.setText(String.valueOf(n_longi));
        
        
        String[] palabras = cadena.split("\\s+");
        int cantPalabras = palabras.length;
        n_totalp.setText(String.valueOf(cantPalabras));
        
        char primeraLetra = cadena.charAt(0);
        char ultimaLetra = cadena.charAt(cadena.length() - 1);
        char letraCentral;

        int longitud = cadena.length();
        int indiceCentralL = longitud / 2;

        if (longitud % 2 == 0) {
            letraCentral = cadena.charAt(indiceCentralL - 1);
        } else {
            letraCentral = cadena.charAt(indiceCentralL);
        }
        n_primeral.setText(String.valueOf(primeraLetra));
        n_centrall.setText(String.valueOf(ultimaLetra));
        n_ultimal.setText(String.valueOf(letraCentral));
        
        String primeraPalabra = palabras[0];
        String ultimaPalabra = palabras[palabras.length - 1];
        String palabraCentral;

        int indiceCentralP = palabras.length / 2;
        if (palabras.length % 2 == 0) {
            palabraCentral = palabras[indiceCentralP - 1];
        } else {
            palabraCentral = palabras[indiceCentralP];
        }
        
        n_primerap.setText(primeraPalabra);
        n_palabrac.setText(palabraCentral);
        n_ultimap.setText(ultimaPalabra);
        
        int contadorA = 0;
        int contadorE = 0;
        int contadorI = 0;
        int contadorO = 0;
        int contadorU = 0;

        for (char c : cadena.toCharArray()) {
            if (c == 'A' || c == 'a' || c == 'á') {
                contadorA++;
            } else if (c == 'E' || c == 'e' || c == 'é') {
                contadorE++;
            } else if (c == 'I' || c == 'i' || c == 'í') {
                contadorI++;
            } else if (c == 'O' || c == 'o' || c == 'ó') {
                contadorO++;
            } else if (c == 'U' || c == 'u' || c == 'ú') {
                contadorU++;
            }
        }

        letra_a.setText(String.valueOf(contadorA));
        letra_e.setText(String.valueOf(contadorE));
        letra_i.setText(String.valueOf(contadorI));
        letra_o.setText(String.valueOf(contadorO));
        letra_u.setText(String.valueOf(contadorU));
        

        int contadorPalabrasPar = 0;
        int contadorPalabrasImpar = 0;
    
        for (String palabra : palabras) {
            if (palabra.length() % 2 == 0) {
                contadorPalabrasPar++; 
            } else {
                contadorPalabrasImpar++;
            }
        }
    
        this.p_par.setText(String.valueOf(contadorPalabrasPar));
        this.p_impar.setText(String.valueOf(contadorPalabrasImpar));
        
        
        Map<Character, String> claveMurcielago = new HashMap<>();
        claveMurcielago.put('a', "7");
        claveMurcielago.put('b', "b"); 
        claveMurcielago.put('c', "3");
        claveMurcielago.put('d', "d"); 
        claveMurcielago.put('e', "5");
        claveMurcielago.put('f', "f"); 
        claveMurcielago.put('g', "8");
        claveMurcielago.put('h', "h"); 
        claveMurcielago.put('i', "4");
        claveMurcielago.put('j', "j");
        claveMurcielago.put('k', "k");
        claveMurcielago.put('l', "6");
        claveMurcielago.put('m', "0");
        claveMurcielago.put('n', "n");
        claveMurcielago.put('o', "9"); 
        claveMurcielago.put('p', "p");
        claveMurcielago.put('q', "q"); 
        claveMurcielago.put('r', "2");
        claveMurcielago.put('s', "s"); 
        claveMurcielago.put('t', "1");
        claveMurcielago.put('u', "3");
        claveMurcielago.put('v', "v"); 
        claveMurcielago.put('w', "w"); 
        claveMurcielago.put('x', "x"); 
        claveMurcielago.put('y', "y"); 
        claveMurcielago.put('z', "z"); 

        // Obtener el texto de entrada del JTextField
        String entrada = this.txt_updated.getText();

        StringBuilder resultado = new StringBuilder();
        for (char c : entrada.toCharArray()) {
            char letra = Character.toLowerCase(c); 
            if (c == ' ') {
                resultado.append(" "); 
            } else if (claveMurcielago.containsKey(letra)) {
                resultado.append(claveMurcielago.get(letra)); 
            } else {
                resultado.append(c); 
            }
        }
        this.txt_murcielago.setText(resultado.toString());
    }//GEN-LAST:event_btn_procesarActionPerformed

    private void jm_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_abrirActionPerformed
        // TODO add your handling code here:
        if (seleccionar.showDialog(null, "abrir")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if (archivo.canRead()){
                if (archivo.getName().endsWith("txt")) {
                    String documento=AbrirArchivo(archivo);
                    this.txt_updated.setText(documento);
                }else{
                    JOptionPane.showMessageDialog(null, "Archivo no Compatible");
                }
            }
        }
    }//GEN-LAST:event_jm_abrirActionPerformed

    private void jm_pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_pegarActionPerformed
        // TODO add your handling code here:
        txt_updated.paste();
    }//GEN-LAST:event_jm_pegarActionPerformed

    private void jm_reemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_reemplazarActionPerformed
        // TODO add your handling code here:
        String buscar = JOptionPane.showInputDialog("Buscar:");
        String reemplazar = JOptionPane.showInputDialog("Reemplazar con:");
        String texto = txt_updated.getText();
        if (buscar != null && reemplazar != null) {
            String nuevoTexto = texto.replaceAll(buscar, reemplazar);
            txt_updated.setText(nuevoTexto); 
        }
    }//GEN-LAST:event_jm_reemplazarActionPerformed

    private void jm_guardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_guardarComoActionPerformed
            if (seleccionar.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
                archivo=seleccionar.getSelectedFile();
                if (archivo.getName().endsWith("txt")) {
                    String Documento=this.txt_updated.getText();
                    String mensaje= GuardarArchivo(archivo, Documento);
                    if (mensaje!=null) {
                        JOptionPane.showMessageDialog(null, mensaje);
                    }else{
                        JOptionPane.showMessageDialog(null, "Archivo Compatible");
                    }    
                }
            }
    }//GEN-LAST:event_jm_guardarComoActionPerformed

    private void jm_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_copiarActionPerformed
        // TODO add your handling code here:
        txt_updated.copy(); 
    }//GEN-LAST:event_jm_copiarActionPerformed

    private void jm_cortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_cortarActionPerformed
        // TODO add your handling code here:
        txt_updated.paste();
    }//GEN-LAST:event_jm_cortarActionPerformed

    private void jm_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_buscarActionPerformed
        // TODO add your handling code here:
        String buscar = JOptionPane.showInputDialog("Buscar:");
        String texto = txt_updated.getText();
        if (buscar != null && texto.contains(buscar)) {
            int index = texto.indexOf(buscar);
            txt_updated.select(index, index + buscar.length());
        } else {
            JOptionPane.showMessageDialog(null, "Texto no encontrado");
        }
    }//GEN-LAST:event_jm_buscarActionPerformed

    private void jm_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_guardarActionPerformed
        // TODO add your handling code here:
        // Verifica si ya se ha seleccionado un archivo
    if (archivo != null) {
        String documento = this.txt_updated.getText(); // Obtiene el texto del JTextArea
        String mensaje = GuardarArchivo(archivo, documento); // Llama a la función para guardar
        if (mensaje != null) {
            JOptionPane.showMessageDialog(null, mensaje); // Muestra mensaje de éxito o error
        } else {
            JOptionPane.showMessageDialog(null, "Archivo guardado correctamente.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Primero debe usar 'Guardar como' para seleccionar un archivo.");
    }
    }//GEN-LAST:event_jm_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_cadenas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_procesar;
    private javax.swing.JLabel clave_murcielago;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jm_abrir;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenuItem jm_buscar;
    private javax.swing.JMenuItem jm_copiar;
    private javax.swing.JMenuItem jm_cortar;
    private javax.swing.JMenu jm_editar;
    private javax.swing.JMenuItem jm_guardar;
    private javax.swing.JMenuItem jm_guardarComo;
    private javax.swing.JMenuItem jm_pegar;
    private javax.swing.JMenuItem jm_reemplazar;
    private javax.swing.JLabel lbl_instruccion;
    private javax.swing.JLabel lbl_tittle;
    private javax.swing.JLabel letra_a;
    private javax.swing.JLabel letra_central;
    private javax.swing.JLabel letra_e;
    private javax.swing.JLabel letra_i;
    private javax.swing.JLabel letra_o;
    private javax.swing.JLabel letra_u;
    private javax.swing.JLabel longitud_texto;
    private javax.swing.JLabel n_centrall;
    private javax.swing.JLabel n_longitud;
    private javax.swing.JLabel n_palabrac;
    private javax.swing.JLabel n_primeral;
    private javax.swing.JLabel n_primerap;
    private javax.swing.JLabel n_totalp;
    private javax.swing.JLabel n_ultimal;
    private javax.swing.JLabel n_ultimap;
    private javax.swing.JLabel p_impar;
    private javax.swing.JLabel p_par;
    private javax.swing.JLabel palabra_central;
    private javax.swing.JLabel palabras_impar;
    private javax.swing.JLabel palabras_par;
    private javax.swing.JLabel primer_letra;
    private javax.swing.JLabel primera_palabra;
    private javax.swing.JLabel repeticiones_a;
    private javax.swing.JLabel repeticiones_e;
    private javax.swing.JLabel repeticiones_i;
    private javax.swing.JLabel repeticiones_o;
    private javax.swing.JLabel repeticiones_u;
    private javax.swing.JLabel total_palabras;
    private javax.swing.JScrollPane txt_field;
    private javax.swing.JTextField txt_murcielago;
    private javax.swing.JTextField txt_updated;
    private javax.swing.JLabel ultima_letra;
    private javax.swing.JLabel ultima_palabra;
    // End of variables declaration//GEN-END:variables
}
